builders:
  jaspr_localizations:
    import: "package:jaspr_localizations/builder.dart"
    builder_factories: ["jasprLocalizationsBuilder"]
    build_extensions: 
      "$lib$":
        - "generated/app_localizations.dart"
    auto_apply: all_packages
    build_to: source
    # Ensure localization generation runs before web compilation so generated
    # localization files exist for imports during subsequent builds.
    runs_before:
      - "build_web_compilers|entrypoint"
      - "build_web_compilers|ddc"
    applies_builders: []
