name: jaspr_localizations
description: Internationalization and localization support for Jaspr applications with ARB file generation.
maintainer: zoocityboy
version: 1.0.0+beta.2
repository: https://github.com/zoocityboy/jaspr_localizations
issue_tracker: https://github.com/zoocityboy/jaspr_localizations/issues
screenshots:
  - description: "Main screen showcasing localization features."
    path: docs/jaspr_localizations.png
  
topics:
  - l10n
  - localization
  - translations
  - language
  - jaspr
environment:
  sdk: ^3.9.0

dependencies:
  jaspr: ^0.21.6
  intl: ^0.20.2
  path: ^1.9.0
  glob: ^2.1.3
  build: ^4.0.2
  universal_web: ^1.1.1+1
  meta: ^1.16.0
  yaml: ^3.1.3
  # sealed_languages: ^2.5.0
  
dev_dependencies:
  jaspr_test: ^0.21.6
  lints: ^6.0.0
  test: ^1.24.0
  build_config: ^1.2.0
  build_runner: ^2.4.13