name: jaspr_localizations
description: Internationalization and localization support for Jaspr applications with ARB file generation.
version: 1.0.0
repository: https://github.com/zoocityboy/jaspr_localizations
# screenshots:
#   - https://raw.githubusercontent.com/zoocityboy/jaspr_localizations/main/screenshots/screenshot1.png
#   - https://raw.githubusercontent.com/zoocityboy/jaspr_localizations/main/screenshots/screenshot2.png

environment:
  sdk: ^3.9.0

dependencies:
  jaspr: ^0.21.6
  intl: ^0.20.2
  path: ^1.9.0
  glob: ^2.1.3
  build: ^4.0.2
  universal_web: ^1.1.1+1
  meta: ^1.16.0
  
dev_dependencies:
  jaspr_test: ^0.21.6
  lints: ^6.0.0
  test: ^1.24.0
  build_config: ^1.2.0
  build_runner: ^2.4.13
